version: '3.9'

services:
  domsommelier-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/domsommelier
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH-SIZE=50
      - MINIO_URL=http://172.18.0.2:9000
      - MINIO_ACCESS_NAME=5q3kIXr0YMJ2yaWV0ER0
      - MINIO_ACCESS_SECRET=Iq5eYZGxONmWFmoXwyjOT0ZF1PHeYzy5ZWkX0LaV
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio-storage:/data
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d domsommelier -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    depends_on:
      - minio
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  minio-storage:
