events {}
http {
    server {
       server_name api.domsommelier.tw1.ru;
       location / {
          proxy_pass http://193.108.115.13:8080;
       }
    }
    server {
       server_name file.domsommelier.tw1.ru;
       location / {
          proxy_pass http://193.108.115.13:9001;
       }
    }
}