spring:
  config:
    encoding: UTF-8
  application:
    name: domsommelier-backend
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO:create-drop}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            trust: smtp.yandex.ru
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

db-init:
  mode: true

jwt:
  expiration: 86400000

app:
  email:
    subject: Ваш код для входа

minio:
  init:
    event:
      files: >
        italian-wine-casino-small.jpg,
        italian-wine-casino-large.jpg,
        french-wine-tasting-large.jpg,
        french-wine-tasting-small.jpg,
        spanish-wine-tasting-large.jpg,
        spanish-wine-tasting-small.jpg
