spring.application.name=domsommelier-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/domsommelier
spring.datasource.username=postgres
spring.datasource.password=123
spring.output.ansi.enabled=ALWAYS

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

minio.url=http://localhost:9000
minio.access.name=minioadmin
minio.access.secret=minioadmin

minio.access-key=minioadmin
minio.secret-key=minioadmin

spring.redis.host=localhost
spring.redis.port=6379
