spring.application.name=domsommelier-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/domsommelier
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

minio.url=http://localhost:9000
minio.access.name=ybgeWmISIHMJaJTWz2Vw
minio.access.secret=r9hdRzxP7woX2vuUrGSTJBRWLWXMWLY5nnaP37kZ

spring.redis.host=redis
spring.redis.port=6379
