#!/bin/sh
# Read MinIO credentials from secret files generated by vault-init
export MINIO_ROOT_USER=$(cat /run/secrets/minio_root_user)
export MINIO_ROOT_PASSWORD=$(cat /run/secrets/minio_root_password)

exec minio "$@"
